vich_uploader:
    db_driver: orm

    mappings:
        quizz_image:
            uri_prefix: /images/quizz
            upload_destination: '%kernel.project_dir%/public/images/quizz'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
